spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/b2c-orders
    username: postgres
    password: postgres
    hikari:
      maxLifetime: 60000
      maximumPoolSize: 5
  liquibase:
    enabled: true
#    change-log: db/changelog/db.changelog-master.xml

